### ISSUE TITLE
Eth showing Not Connected

### ISSUE THREAD

**Issue by cameronbrister** [mrodalgaard/alfred-network-workflow#1]
Hi - I'm running OS X 10.11.4 on a Late 2013 Mac Pro. When I try to use "Eth", it shows Not Connected, although I have a DHCP address on Eth1. Same goes if I set a static or move to Eth2...

**Comment by codegrau** [comment]
Hi there. Have to reopen this one please. Connected to ethernet via USB-(C) Ethernet Dongle but still "not connected" and DNS changer commands only to WiFi

```
#networksetup -listallhardwareports
Hardware Port: USB 10/100/1000 LAN
Device: en7
Ethernet Address: de:ad:be:ef:fe:ed
```

**Comment by mrodalgaard** [comment]
@codegrau thank you for the command output. I have added a match for ethernet connection matching your setup over usb. It will be added to next release.
