### ISSUE TITLE
How to I install this workflow? 

### ISSUE THREAD

**Issue by SebastianBehrens** [mrodalgaard/alfred-network-workflow#10]
Could you create a .alfredworkflow version or add a little how-to-use section in your Readme.md-file?

**Comment by jpuris** [comment]
Go to https://github.com/mrodalgaard/alfred-network-workflow/releases and choose `Network.alfredworkflow` for the version you want to download.

Once downloaded, double click on the download and it will open in Alfred.

**Comment by SebastianBehrens** [comment]
Thank you.
