### ISSUE TITLE
VPN Connection

### ISSUE THREAD

**Issue by wraith1385** [mrodalgaard/alfred-network-workflow#13]
Hello, I recently installed your workflow, but I'm having issues with the VPN connection. I have a single L2TP VPN and your workflow can list it ok, but when I try to connect I get the following error message:

The server is unreachable. Try reconnecting. If the problem continues, verify your settings and contact your Administrator.

It connects fine when I do it the normal way.

**Comment by jpuris** [comment]
Take a look at https://github.com/mrodalgaard/alfred-network-workflow/pull/12

**Comment by wraith1385** [comment]
I've downloaded the latest release since that commit ans I still get the same error.

**Comment by mrodalgaard** [comment]
@wraith1385 I have not released a build with the fix yet. I will do it as soon as I get the time.

**Comment by wraith1385** [comment]
Ah, sorry, I read the releases page wrong.

**Comment by mrodalgaard** [comment]
@wraith1385 @jpuris ; A new release 1.3.0 has been published with this fix https://github.com/mrodalgaard/alfred-network-workflow/releases/tag/v1.3.0

**Comment by wraith1385** [comment]
I'm still getting this error on the latest release
