### ISSUE TITLE
VPN Connection

### ISSUE THREAD

**Issue by wraith1385** [mrodalgaard/alfred-network-workflow#14]
I'm still getting the error below on the latest release when trying to connect my VPN.  

The server is unreachable. Try reconnecting. If the problem continues, verify your settings and contact your Administrator.

**Comment by mrodalgaard** [comment]
@jpuris and @kerma; I am unable to reproduce the above behaviour. Do any of you see the same behaviour after #12 ?

**Comment by jpuris** [comment]
@wraith1385 What VPN type are you using?

I do not see issues with IPSec.

**Comment by wraith1385** [comment]
I have an L2TP VPN

**Comment by jpuris** [comment]
I will try to find some L2TP VPN service and see, if I can reproduce this.

**Comment by kerma** [comment]
@wraith1385 Can you please run the following in terminal and paste the results here:

`scutil --nc show "your-vpn-name"`
`networksetup -connectpppoeservice "your-vpn-name"`

The first should list info about the vpn. This get parsed and based on it decided which utility to use for connecting.

Second tries to connect to the VPN. If it fails, maybe it gives more info about why exactly.

**Comment by wraith1385** [comment]
Chimaera:~ Seth$ scutil --nc show "VPN (L2TP)"
* (Disconnected)   0EBAF065-DF53-43AF-A952-EA70B96644BE PPP --> L2TP       "VPN (L2TP)"                     [PPP:L2TP]
PPP <dictionary> {
  ACSPEnabled : 1
  CommDisplayTerminalWindow : 0
  CommRedialCount : 1
  CommRedialEnabled : 0
  CommRedialInterval : 5
  CommUseTerminalScript : 0
  DialOnDemand : 0
  DisconnectOnFastUserSwitch : 1
  DisconnectOnIdle : 0
  DisconnectOnIdleTimer : 600
  DisconnectOnLogout : 1
  DisconnectOnSleep : 0
  IPCPCompressionVJ : 0
  IdleReminder : 0
  IdleReminderTimer : 1800
  LCPEchoEnabled : 1
  LCPEchoFailure : 15
  LCPEchoInterval : 20
  Logfile : /var/log/ppp.log
  VerboseLogging : 0
}

For the second command I get the same popup that I get when I try to connect via the alfred extension.  

"The server is unreachable. Try reconnecting. If the problem continues, verify your settings and contact your Administrator."

I can still connect fine through the VPN icon in the Menubar.

**Comment by kerma** [comment]
@wraith1385 is it possible that somehow the icon on the menu bar actually connects to a different VPN? Do you have more than one set up under Network?

I'm asking because my output looks something like this:

```
* (Disconnected)   2BDED74D-C104-43D7-9E20-AE2FE7890187 PPP --> L2TP       "DevVPN"                         [PPP:L2TP]

PPP <dictionary> {
  ACSPEnabled : 1
  AuthName : my@email.com
  AuthPassword : 2BDED74B-C104-43D7-9E20-EE2FF7890187
  AuthPasswordEncryption : Keychain
  CommDisplayTerminalWindow : 0
  CommRedialCount : 1
  CommRedialEnabled : 0
  CommRedialInterval : 5
  CommRemoteAddress : <ip-address-here>
  CommUseTerminalScript : 0
  DialOnDemand : 0
  DisconnectOnFastUserSwitch : 1
  DisconnectOnIdle : 0
  DisconnectOnIdleTimer : 600
  DisconnectOnLogout : 1
  DisconnectOnSleep : 0
  IPCPCompressionVJ : 0
  IdleReminder : 0
  IdleReminderTimer : 1800
  LCPEchoEnabled : 1
  LCPEchoFailure : 15
  LCPEchoInterval : 20
  Logfile : /var/log/ppp.log
  VerboseLogging : 0
}
```

Your output is missing auth info and the server where it should connect to.

**Comment by wraith1385** [comment]
I only have 1 VPN setup.  When I look at the VPN in OS X's Network Preferences, it has all of the auth info setup correctly.

**Comment by wraith1385** [comment]
Ok, so I figured it out thanks to you prodding me to look at my VPN.  Apparently I had a different configuration created for the VPN besides the default one and that was where all of the auth info was.  Once I moved all of that over to the default configuration everything now works.

I appreciate the help and apologize for wasting anyone's times.

**Comment by mrodalgaard** [comment]
Thank you @kerma . Great job debugging this.
