### ISSUE TITLE
when connect/disconnect vpn workflow asks for update

### ISSUE THREAD

**Issue by alex-popov-tech** [mrodalgaard/alfred-network-workflow#17]
hello!

Using that workflow for a while, its super cool!
Only thing which bothers me is when I'm toggling Wireshark VPN's it always asking me for update/import settings and that window from alfred always appears...when using 1.3.0

Any ideas how to fix that?

**Comment by mrodalgaard** [comment]
Hi, I believe this might be caused by OneUpdater which is used internally to update if there are a new version of this workflow available. You say "... asking me for update/import settings"; how is it asking you? Can you paste a screenshot here? Which window from alfred is showing?

**Comment by mrodalgaard** [comment]
I have just released a [new version](https://github.com/mrodalgaard/alfred-network-workflow/releases/tag/v1.4.0) where I made sure the internal version is set to 1.4.0 as well.

**Comment by alex-popov-tech** [comment]
hey, thanks for such a quick answer and a fix!
i just tried it, and now it works! so I cannot send a screenshot :D 
anyways, thank you so mush, this plugin is super helpful!
