### ISSUE TITLE
Ethernet connection not detected — USB adapter

### ISSUE THREAD

**Issue by cataclysmicvoid** [mrodalgaard/alfred-network-workflow#20]
Testing on a 2021 MacBook Pro 14 via a USB-C > USB-A > Ethernet adapter (appearing as en7) the "ethernet" command returns as false even when connected

If memory serves I used this workflow on an M1 Mac Mini without issue (has a hardware RJ45 connector)

macOS 12.1, Alfred 4.6.2

**Comment by mrodalgaard** [comment]
Hi, that is probably because the hardware name of your ethernet adapter is something weird :) Could you write the output of running `networksetup -listallhardwareports` in your Terminal?

**Comment by cataclysmicvoid** [comment]
Redacted MACs. By chance just added this AX adapter (it's an Amazon Basics USB-C > Ethernet adapter) today. The original adapter is once of the other ones. 
```
Hardware Port: Ethernet Adapter (en4)
Device: en4
Ethernet Address: b6:e6:

Hardware Port: Ethernet Adapter (en5)
Device: en5
Ethernet Address: b6:e6:

Hardware Port: AX88179A
Device: en8
Ethernet Address: a0:ce:

Hardware Port: Ethernet Adapter (en6)
Device: en6
Ethernet Address: b6:e6:

Hardware Port: Wi-Fi
Device: en0
Ethernet Address: f8:4d:

Hardware Port: Thunderbolt 1
Device: en1
Ethernet Address: 36:55:

Hardware Port: Thunderbolt 2
Device: en2
Ethernet Address: 36:55:

Hardware Port: Thunderbolt 3
Device: en3
Ethernet Address: 36:55:

Hardware Port: Thunderbolt Bridge
Device: bridge0
Ethernet Address: 36:55:

VLAN Configurations
===================
```
