### ISSUE TITLE
DNS requires admin rights with OSX 12.6

### ISSUE THREAD

**Issue by Sebastian-Hojas** [mrodalgaard/alfred-network-workflow#22]
```
> networksetup -setdnsservers 8.8.8.8
** Error: Command requires admin privileges.
```

When setting a DNS server, the script fails because `networksetup` requires admin privileges with OSX 12.6.

**Comment by mrodalgaard** [comment]
Hi @Sebastian-Hojas,

You are right. Apparently changes were made to `networksetup` all the way back in macOS Big Sur (see https://blog.kandji.io/managing-network-settings-on-macos-big-sur-and-mac-address-randomization-in-ios-14#limitations-for-standard-users).

I don't think there is much for me to do other than inform users of this workflow. I tried to force a password dialog without luck - if you know I way to achieve this I am open for suggestions.

Most functionality of this workflow will work without your user being administrator on your machine (see if your user is set as `Admin` or `Standard` in "System Settings.app" -> "Users & Groups"), but actions which changes network settings might fail if you are only a standard user.

I will add this information to the readme under limitations.
