### ISSUE TITLE
DNS does not work on Ventura

### ISSUE THREAD

**Issue by WladyX** [mrodalgaard/alfred-network-workflow#24]
I guess this is because wifi interface does not get matched:
```
LIST=$(networksetup -listallhardwareports) getWifiInterface "$LIST"
getWifiInterface:3: no matches found: en[0-9]
```

**Comment by mrodalgaard** [comment]
Hi @WladyX,

Could you post the output of your `networksetup -listallhardwareports`?

**Comment by mrodalgaard** [comment]
Okay. There is one big problem with setting DNS, which is that DNS is set on a connection (wifi OR ethernet1 OR ethernet2, etc.). Current implementation just sets it on wifi, which of course is not always what the user wants :(.

Tell me if that is what you are experiencing and try below one-liners. Also tell me how it is not working; alfred input + expected result + actual result.

`echo "$(networksetup -listallhardwareports)" | grep -A 2 -E "Airport$|Wi-Fi$" | grep -Eo "AirPort|Wi-Fi"` This is currently how the Wi-Fi port is found. Should output "Wi-Fi" in your case.

`echo "$(networksetup -listallhardwareports)" | grep -A 2 -E "LAN$|Lan$|Ethernet$" | awk '/Hardware / {print substr($0, index($0, $3))}'` This is currently how the first ethernet port is found. This should output "USB 10/100/1000 LAN" in your case.

`networksetup -getdnsservers "Wi-Fi"` should output the current dns set on your wifi.

`networksetup -getdnsservers "USB 10/100/1000 LAN"` should output the current dns set on your ethernet.

**Comment by WladyX** [comment]
except the last command, everything was as you said, however i have a dns set in resolv.conf.
```
❯ echo "$(networksetup -listallhardwareports)" | grep -A 2 -E "Airport$|Wi-Fi$" | grep -Eo "AirPort|Wi-Fi"
Wi-Fi
❯ echo "$(networksetup -listallhardwareports)" | grep -A 2 -E "LAN$|Lan$|Ethernet$" | awk '/Hardware / {print substr($0, index($0, $3))}'
USB 10/100/1000 LAN
 14:19:52
❯ networksetup -getdnsservers "Wi-Fi"
8.8.8.8
8.8.4.4
❯ networksetup -getdnsservers "USB 10/100/1000 LAN"
There aren't any DNS Servers set on USB 10/100/1000 LAN.
❯ grep nameserver /etc/resolv.conf
nameserver 192.168.1.3
```

When i changed the DNS with your workflow i expected it to be reflected in resolv.conf, which is not updated.
When using the workflow, the status/output of `networksetup -getdnsservers "Wi-Fi"` it is indeed updated correctly.
I would of course like to set the DNS on the LAN connection.
I'm pretty sure that before upgrading to Ventura this workflow changed the DNS correctly (reflected in resolv.conf) even when i had both WiFi and LAN enabled.
Thank you very much for your support!

**Comment by mrodalgaard** [comment]
This workflow has never touched `resolv.conf`. It sets the DNS using `networksetup -setdnsservers ${NAME%,*} $DNS` where `$NAME` is currently your wifi port. Apple might have automatically reflected the changes to `resolv.conf` but as far as I can read that is pretty deprecated (https://developer.apple.com/forums/thread/675752 ).

If you go into your ethernet connection in System Preferences and set DNS nameservers, they will appear when calling `networksetup -getdnsservers "USB 10/100/1000 LAN"`, so all your output from above is as expected.

At some point I will have a look at being able to set DNS for all connections.

<img width="827" alt="Screenshot 2023-09-20 at 16 07 39" src="https://github.com/mrodalgaard/alfred-network-workflow/assets/659763/b874c31f-775d-4011-8813-6fab6883b535">

**Comment by WladyX** [comment]
I have DNS for eth via DHCP:
<img width="1174" alt="CleanShot 2023-09-20 at 17 29 44@2x" src="https://github.com/mrodalgaard/alfred-network-workflow/assets/1106868/13a96a45-b0e8-4cf8-adc2-19a613823bea">
Anyway, this is unrelated to your workflow i guess.
Yeah, updating the DNS for all connections, or for the "main" one at least would be great.
Thank you!

**Comment by WladyX** [comment]
I hacked it for now :)
in wifiCommon.sh I've put:
```
NAME=$(networksetup -listnetworkserviceorder | grep "(1)" | sed 's/(1) //')
```

This works, but has one bug, one network can be top priority even if it is not connected, so if your top priority network is not connected then it replaces the DNS for a connection that you are not using :)
Thank you again for your time.

**Comment by mrodalgaard** [comment]
I have solved this with the following, which will be added to next release:

```sh
getPrimaryInterfaceName() {
  local INTERFACE=$(getEthernetInterface)
  if [ $(getEthernetState "$INTERFACE") != 0 ]; then
    echo "$(getEthernetName)"
  else
    echo "$(getWifiName)"
  fi
}
```
