### ISSUE TITLE
DNS switcher using networksetup -setdnsservers

### ISSUE THREAD

**Issue by oalders** [mrodalgaard/alfred-network-workflow#3]
Thanks for all of your work on this.  I saw "DNS switcher using networksetup -setdnsservers" on the Packal TODO list and I wanted to give it a 👍 

I typically want to toggle between a couple of sets of DNS servers.  I do this via shell scripts right now, but doing it via Alfred would be great.

**Comment by mrodalgaard** [comment]
Hi @oalders,

DNS switcher is already implemented and available with commit 1d94e030b7317ffb6675de4cbcf71e7975c3bf4b , but I just wanted to test it a bit before publishing an update to packal. You can try it out by cloning this repo and replacing it with the your existing Network workflow.

**Comment by oalders** [comment]
Hi @mrodalgaard,

Great!  I just installed it and it works nicely.  This will make my life easier.  :)  

As an aside, when I click on the "edit DNS" option, Tunnelblick really goes nuts.  Including here just as an FYI.

<img width="424" alt="screenshot 2016-05-30 11 48 40" src="https://cloud.githubusercontent.com/assets/96205/15653810/4799cf2a-265d-11e6-9c34-89f8ad9ad403.png">

<img width="422" alt="screenshot 2016-05-30 11 50 49" src="https://cloud.githubusercontent.com/assets/96205/15653815/4d8ce11a-265d-11e6-895d-aa8f28ba1c5e.png">
