### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by xilopaint** [mrodalgaard/alfred-network-workflow#6]
If so, I'll submit a PR.

**Comment by mrodalgaard** [comment]
Yes. It is still maintained. A PR is very welcome.

**Comment by xilopaint** [comment]
Well, now I see this is an Alfred 2 workflow. If I make any change it will lose compatibility with Alfred 2 since I'm an Alfred 3 user.

**Comment by xilopaint** [comment]
@mrodalgaard is that a problem?

**Comment by mrodalgaard** [comment]
See #7
